weapons = {
  melee = {
    'weapon_dagger',
    'weapon_bat',
    -- 'weapon_battleaxe',
    'weapon_bottle',
    'weapon_crowbar',
    'weapon_hatchet',
    'weapon_hammer',
    'weapon_knife',
    'weapon_knuckle',
    'weapon_nightstick',
    'weapon_flashlight',
    'weapon_machete',
    -- 'weapon_wrench',
    -- 'weapon_poolcue',
    'weapon_golfclub',
    'weapon_switchblade'
  },
  pistols = {
    'weapon_stungun',
    'weapon_flaregun',
    'weapon_combatpistol',
    'weapon_revolver',
    'weapon_pistol',
    'weapon_pistol50',
    'weapon_heavypistol',
    'weapon_marksmanpistol',
    'weapon_snspistol',
    'weapon_vintagepistol',
    'weapon_appistol',
  },
  submachines = {
    'weapon_assaultsmg',
    'weapon_combatpdw',
    -- 'weapon_minismg',
    'weapon_smg',
    'weapon_microsmg',
    'weapon_machinepistol',
  }
}
